name: Build Android APK
on:
  push:
    paths:
      - 'android/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer Docker
        run: |
          chmod -R 777 .
          
          mkdir -p $HOME/.buildozer
          mkdir -p $HOME/.android
          mkdir -p $HOME/.gradle
          mkdir -p $HOME/.kivy
          
          chmod -R 777 $HOME/.buildozer
          chmod -R 777 $HOME/.android
          chmod -R 777 $HOME/.gradle
          chmod -R 777 $HOME/.kivy

          USER_ID=$(id -u)
          GROUP_ID=$(id -g)
          
          docker run --rm \
            --user $USER_ID:$GROUP_ID \
            --entrypoint /bin/sh \
            -v "$(pwd)":/home/user/hostpython \
            -v "$HOME/.buildozer":/home/user/.buildozer \
            -v "$HOME/.android":/home/user/.android \
            -v "$HOME/.gradle":/home/user/.gradle \
            -v "$HOME/.kivy":/home/user/.kivy \
            -e REPO_PATH=/home/user/hostpython \
            -e HOME=/home/user \
            -e GRADLE_USER_HOME=/home/user/.gradle \
            kivy/buildozer \
            -c "
            # 1. 在挂载的工作目录下创建虚拟环境（这里肯定有权限）
            cd /home/user/hostpython &&
            python3 -m venv myenv &&
            . myenv/bin/activate &&
            
            # 2. 安装依赖
            pip install --upgrade pip &&
            pip install buildozer cython==0.29.36 appdirs 'colorama>=0.3.3' jinja2 'sh>=1.10,<2.0' build toml packaging setuptools &&
            
            # 3. 开始编译
            cd android && 
            export USE_CCACHE=0 &&
            yes | buildozer android debug
            "

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: crypto-widget-apk
          path: android/bin/*.apk
