name: Build Android APK
on:
  push:
    paths:
      - 'android/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer Docker
        run: |
          chmod -R 777 .
          mkdir -p $HOME/.buildozer
          chmod -R 777 $HOME/.buildozer

          USER_ID=$(id -u)
          GROUP_ID=$(id -g)
          
          docker run --rm \
            --user $USER_ID:$GROUP_ID \
            --entrypoint /bin/sh \
            -v "$(pwd)":/home/user/hostpython \
            -v "$HOME/.buildozer":/home/user/.buildozer \
            -e REPO_PATH=/home/user/hostpython \
            -e HOME=/home/user \
            kivy/buildozer \
            -c "
            # 先给 pip 升级并安装必要的依赖，加上 --user 确保装在用户目录下
            /home/user/.venv/bin/python3 -m pip install --user --upgrade pip &&
            /home/user/.venv/bin/python3 -m pip install --user appdirs 'colorama>=0.3.3' jinja2 'sh>=1.10,<2.0' build toml packaging setuptools &&
            
            # 进入目录开始编译
            cd /home/user/hostpython/android && 
            buildozer android debug
            "

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: crypto-widget-apk
          path: android/bin/*.apk
